name: atualiza_orcamento
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup_r
        uses: r-lib/actions/setup-r@v2
      - name: install_packages
        run: Rscript -e 'install.packages(c("readxl", "dplyr", "openxlsx", "lubridate"))'
      - name: run_script
        run: Rscript orcamento/atualiza_base.R
      - name: save_excel
        run: |
          git config --global user.name "Robo-BI"
          git config --global user.email "actions@github.com"
          git add orcamento/Execucao_Orcamentaria_Atualizada.xlsx
          git commit -m "Dados atualizados" || echo "Sem alteracoes"
          git push
