name: Atualizar Base de Orcamento

on:
  schedule:
    - cron: '0 8 * * *' # Roda todo dia às 08:00 AM
  workflow_dispatch: # Permite rodar manualmente no botão do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para salvar o arquivo de volta no repositório

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias do sistema Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Instalar pacotes do R
        run: |
          install.packages(c("readxl", "dplyr", "readr", "lubridate"), repos='https://cloud.r-project.org')
        shell: Rscript {0}

      - name: Rodar script de atualizacao
        run: Rscript orcamento/atualiza_base.R
      - name: Commit e Push dos resultados
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add orcamento/Execucao_Orcamentaria_Atualizada.csv
          git commit -m "Dados atualizados: $(date)" || echo "Sem mudanças para salvar"
          git push
