name: Atualizar Dados BI Orçamento

on:
  schedule:
    - cron: '0 5 * * *' # Roda todo dia às 5 da manhã (horário UTC)
  workflow_dispatch: # Permite que você rode manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
      
      - name: Instalar Pacotes R
        run: |
          Rscript -e 'install.packages(c("readxl", "dplyr", "openxlsx", "lubridate"))'
      
      - name: Executar Script R
        run: Rscript orcamento/atualiza_base.R
      
      - name: Salvar Arquivo Gerado
        run: |
          git config --global user.name "Robo-BI"
          git config --global user.email "actions@github.com"
          git add orcamento/Execucao_Orcamentaria_Atualizada.csv
          git commit -m "Dados atualizados automaticamente" || echo "Sem alterações para salvar"
          git push
